basic front
sbriclot/fleet pull request #50
Opened 2021-01-28 19:32 UTC by Mordhin

![image](https://user-images.githubusercontent.com/68302860/106188566-6f51da00-61a7-11eb-8980-07585651d6f9.png)

J'ai créé le style des typos, quelques éléments de base et une nouvelle navbar.
J'ai supprimé bootstrap aussi car il créé beaucoup de conflit. Je l'ai supprimé avec '$yarn remove bootstrap', je pense qu'il faut aussi le faire sur la prod.

2021-01-28 20:09 UTC, sbriclot approved these changes

2021-01-28 20:13 UTC, sbriclot commented
J'aime bien le résultat, c'est sobre et propre.
Je testerai ça demain matin sur mon PC, pour voir si Bootstrap me pose problème ou si je dois aussi passer la commande yarn remove. Ca nous dira si il faut craindre quelque chose avec la prod.

2021-01-28 20:33 UTC, JPS09 reviewed
ça ne fonctionne pas de mon côté : 
# Terminal
![image](https://user-images.githubusercontent.com/58084593/106195300-4255f500-61b0-11eb-9f92-09db8dbc93d2.png)

# LocalHost
![image](https://user-images.githubusercontent.com/58084593/106195463-77624780-61b0-11eb-8b74-e3f5eb83c7f3.png)

2021-01-29 11:10 UTC, Mordhin commented
Pour ton problème de nil class, as-tu db:seed ?

2021-01-29 12:10 UTC, sbriclot commented
Le problème arrive quand tu n'es pas loggé (comme après un **db:seed**), dans ce cas current_user est NIL, donc tu ne pas appelé de méthode dessus.
Il faut que tu encapsules ton div avec une condition pour tester current_user, comme ça :
```
<% unless current_user.nil? %>
  <div><%= current_user.email %> </div>
<% end %>
```
Je viens de tester en local, ça fonctionne.

Sinon, pas de problème chez moi avec Bootstrap, juste passer une commande **yarn install --check-files** pour mettre mon fichier à jour (suggéré en lançant un **rails s**) et c'est bon. Par contre, les simple_form sont bien moches maintenant.

2021-01-29 12:14 UTC, sbriclot commented
Sinon, je constate que suite au merge de mon change, il y a un léger conflit.
J'avais créé une classe CSS pour pouvoir masquer certains magasins dans mon index, tu pourras la conserver dans la version finale, cette classe pourra aussi être utile dans la vehicle#index, pour afficher/masquer les véhicules vendus.

2021-02-01 15:03 UTC, JPS09 requested changes
Beau boulot dans l'ensemble, je pense que conserver une copie de la nav bar originelle n'est peut-être pas utile vu que le fichier ne sera pas utilisé par la suite malgré l'incroyable classe du CEO du Wagon ^^

2021-02-01 15:03 UTC, JPS09 commented on app/views/shared/_navbar.html.erb
> +    <i class="fas fa-bars"></i>
Cette modif ne permet plus d’accès à une interface de connexion, ce qui est dommage et nous empêche la différenciation des utilisateurs et de leurs véhicules.
Aussi voici une suggestion à peaufiner , surtout concernant le CSS, concernant ce problème et le bug lorsqu'un utilisateur n'est pas connecté

```suggestion
<div class="navbar">
  <%= link_to vehicles_path do %>
    <div><h1>Fleet</h1></div>
  <% end %>
  <div class="navbar-right">
     <% if user_signed_in? %>
        <div><%= current_user.email %> </div>
        <i class="fas fa-bars"></i>
     <% else %>
         <%= link_to "Login", new_user_session_path %>
      <% end %>
   </div>
</div>
   
```

2021-02-01 15:09 UTC, sbriclot commented on app/views/shared/_navbar.html.erb
> +    <i class="fas fa-bars"></i>
Bien vu le **user_signed_in?**, j'avais totalement oublié ce helper.

2021-02-02 17:16 UTC, Mordhin commented
J'ai validé ta modif @JPS09 et j'ai delete la navBar originale (je l'avais gardé au cas où, car sur hops on avait eu beaucoup de mal avec Adrien à en faire une propre avec un menu déroulant). Je pense qu'on peut merge ?

2021-02-02 18:02 UTC, JPS09 requested changes

2021-02-02 18:02 UTC, JPS09 commented on app/views/shared/_navbar.html.erb
>  </div>
Super cool,merci à toi pour ce taf! 
Il faudrait juste enlever les deux tags de fermeture de divs qui sont en trop, j'ai pas fait gaffe avec la suggestion désolé :/ On pourra merge juste après sans soucis pour moi :) 

```suggestion
```

2021-02-02 21:29 UTC, merged