Invoice CRUD
sbriclot/fleet pull request #52
Opened 2021-02-02 13:08 UTC by JPS09

2021-02-02 17:24 UTC, Mordhin approved these changes

2021-02-02 17:25 UTC, Mordhin commented
C'est trop cool !

2021-02-02 19:28 UTC, sbriclot commented
One important function is missing.
When you add or edit an invoice, the field _Vehicle.total_expense_ must be updated automatically.

2021-02-03 13:05 UTC, JPS09 commented
> 
> 
> One important feature is missing.
> When you add or edit an invoice, the field _Vehicle.total_expense_ must be updated automatically.

I added the feature, feel free to have a look and check on your side if it works properly. I checked the main issue and it seems to be working fine on my side but I may have missed something

2021-02-03 19:15 UTC, sbriclot requested changes

2021-02-03 19:15 UTC, sbriclot commented on app/controllers/invoices_controller.rb
> +      redirect_to vehicle_invoice_path(@vehicle, @invoice), notice: 'Facture créee'
_total_expenses_ calculation is not at the right place. If the invoice is invalid, you will call the method **create** twice (or more), and the total will be increased each time the method is called.
Please move line 21 inside the _IF_ in order to update the total only when the invoice is valid ans saved.

Same change to do in the method **update**, move the call to _old_invoice_price_ inside the _IF_.

2021-02-03 19:22 UTC, sbriclot commented
If you received a mail about my code review, don't take care of it for the moment, I have a doubt about the position of total_expenses calculation, but I want to test your branch first, I'm not sure how rails manage commit and rollback in this case.

2021-02-03 19:59 UTC, JPS09 commented
> If you received a mail about my code review, don't take care of it for the moment, I have a doubt about the position of total_expenses calculation, but I want to test your branch first, I'm not sure how rails manage commit and rollback in this case.

Don't worry, I didn't received a notification.
Feel free to suggest a better way, I think that mine might leave some edge cases unattended but I can't pinpoint which ones

2021-02-03 22:08 UTC, sbriclot requested changes

2021-02-03 22:08 UTC, sbriclot commented on app/controllers/invoices_controller.rb
>    end
```suggestion
  def old_invoice_price(old_price)
    return if old_price == @invoice.price

    @vehicle.total_expenses += @invoice.price - old_price
    @vehicle.save
  end
```

2021-02-03 22:11 UTC, sbriclot requested changes

2021-02-03 22:11 UTC, sbriclot commented on app/controllers/invoices_controller.rb
> +      redirect_to vehicle_invoice_path(@vehicle, @invoice), notice: 'Facture créee'
```suggestion
  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.vehicle = @vehicle
    if @invoice.save
      old_invoice_price(0)
      redirect_to vehicle_invoice_path(@vehicle, @invoice), notice: 'Facture créee'
```

2021-02-03 22:13 UTC, sbriclot requested changes

2021-02-03 22:13 UTC, sbriclot commented on app/controllers/invoices_controller.rb
> +      redirect_to vehicle_invoice_path(@vehicle, @invoice), notice: 'Facture mise à jour'
```suggestion
  def update
    # Si il y a modification du prix, soustrait l'ancien prix et le remplace par le nouveau
    old_price = @invoice.price
    if @invoice.update(invoice_params)
      old_invoice_price(old_price)
      redirect_to vehicle_invoice_path(@vehicle, @invoice), notice: 'Facture mise à jour'
```

2021-02-03 22:24 UTC, sbriclot commented
**total_expenses** is not calculated at the right place and the change is not saved due to the missing command @vehicle.save.
Please have a look at the proposals for :
* the new name for the method **old_invoice_price**, which become **update_total_expenses**
* the method **update_total_expenses**, which can be used for invoice creation and update
* the calls to this method in **create** and **update**

2021-02-04 07:35 UTC, JPS09 commented
> 
> 
> **total_expenses** is not calculated at the right place and the change is not saved due to the missing command @vehicle.save.
> Please have a look at the proposals for :
> 
>     * the new name for the method **old_invoice_price**, which become **update_total_expenses**
> 
>     * the method **update_total_expenses**, which can be used for invoice creation and update
> 
>     * the calls to this method in **create** and **update**

Thank you for your suggestion, I committed them to the branch. I will work on the layout before Monday if I can.

2021-02-04 09:34 UTC, sbriclot approved these changes

2021-02-04 09:34 UTC, sbriclot commented
Good job, works fine now, can be merged.

2021-02-08 12:25 UTC, JPS09 commented
I will work on the layout after merging this one since bootstrap is still in my branch and frankly, is getting in my way.

2021-02-09 20:28 UTC, JPS09 commented
When you can, can you give this PR a last review before it can be merged? Thank you!

2021-02-10 12:30 UTC, sbriclot commented
Works fine.
Maybe a last validation rule to add, to avoid dates in the future (for me it's not possible to add an invoice before its edition).
What do you think about this proposal ?

2021-02-10 14:21 UTC, JPS09 commented
> 
> 
> Works fine.
> Maybe a last validation rule to add, to avoid dates in the future (for me it's not possible to add an invoice before its edition).
> What do you think about this proposal ?

I totally agree, I just added a new validation to prevent this, please have a look :)

2021-02-10 14:44 UTC, sbriclot requested changes

2021-02-10 14:44 UTC, sbriclot commented on app/models/invoice.rb
> +    errors.add(:date, "Une facture ne peut être créée depuis le future")
```suggestion
    errors.add(:date, "Une facture ne peut être créée dans le futur")
```

2021-02-10 17:38 UTC, sbriclot approved these changes

2021-02-10 17:52 UTC, merged