Reminders full CRUD and code cleaning
sbriclot/fleet pull request #71
Opened 2021-02-21 09:16 UTC by sbriclot

Full CRUD for reminders :
- list all reminders (will see later how to manage obsolete reminders)
- display remaining km and/or limit date (in red if 1 target is reached)
- for new reminders, no default date, and creation_km = actual km of the vehicle
- usual validations rules

Some code cleaning in maintenance_plan/maintenance (french interface, missing final empty lines).

2021-03-02 16:47 UTC, JPS09 requested changes
Little suggestions, please have a look

2021-03-02 16:47 UTC, JPS09 commented on app/controllers/reminders_controller.rb
> +  def populate_index
I think that it would be better to use `before_action` for this method whenever it is possible to clear the code

- [ ] index
- [ ] edit

2021-03-02 16:47 UTC, JPS09 commented on app/controllers/reminders_controller.rb
> +
```suggestion
before_action :populate_index, only: %i[index edit]
```

2021-03-02 16:47 UTC, JPS09 commented on app/controllers/reminders_controller.rb
> +    populate_index
```suggestion
```

2021-03-02 16:47 UTC, JPS09 commented on app/controllers/reminders_controller.rb
> +    populate_index
```suggestion
```

2021-03-03 08:13 UTC, sbriclot commented
You're right, I did the change for Reminders, and also for Maintenance_Plans, Maintenances and Operations.

2021-03-03 09:09 UTC, JPS09 approved these changes
ok for me, can be merged right away :)

2021-03-04 07:56 UTC, merged