Sale date and km validation rules
sbriclot/fleet pull request #72
Opened 2021-02-21 09:41 UTC by sbriclot

Sale_date can't be lower than the purchase_date nor in the future.
Sale_km can't be lower than purchase_km.
Change redirection for methods create and update (to vehicle#show instead of vehicle#index).

2021-03-02 16:39 UTC, JPS09 requested changes

2021-03-02 16:39 UTC, JPS09 commented on app/controllers/vehicles_controller.rb
>        @vehicle.save
No need to call `.save` since `.update` already does it
See here : [Update](https://guides.rubyonrails.org/active_record_basics.html#update)

2021-03-03 08:19 UTC, sbriclot commented
You're right, I did the chnage for Vehicles and for Shops (copied form Vehicles).

2021-03-03 09:07 UTC, JPS09 approved these changes
Fine for me, it can be merged :)

2021-03-04 07:59 UTC, merged