Vehicle fuels crud
sbriclot/fleet pull request #73
Opened 2021-03-06 08:47 UTC by sbriclot

In the vehicle#show, display the full Fuels list, and check the fuels already assigned to the vehicle.
Everytime a fuel is checked/unchecked, submit the form to rebuild the table Vehicle_Fuels for the current vehicle.
Use CSS to display the checkboxes like buttons.

2021-03-30 11:32 UTC, JPS09 commented on app/views/vehicles/show.html.erb
> +  <%= form_for @vehicle, url: upd_vehicle_fuels_vehicle_path, method: :post, :html => { :id => "vf-update" } do %>
For coherency, I suggest that we stick to one way of writing symbols
```suggestion
  <%= form_for @vehicle, url: upd_vehicle_fuels_vehicle_path, method: :post, html: { id: "vf-update" } do %>
```

2021-03-30 11:32 UTC, JPS09 commented on app/views/vehicles/show.html.erb
> +      <%= check_box_tag fuel_name, fuel_id, fuel["checked"], :name => fuel_name, class: 'tag-selector' %>
```suggestion
      <%= check_box_tag fuel_name, fuel_id, fuel["checked"], name: fuel_name, class: 'tag-selector' %>
```

2021-03-30 11:55 UTC, JPS09 requested changes
Some refacto, I still need to find a way to avoid reload when checking fuels

2021-03-30 12:33 UTC, sbriclot commented
> 
> 
> Some refacto, I still need to find a way to avoid reload when checking fuels

2021-03-30 12:50 UTC, sbriclot commented
Wrong click, sorry for the close/reopen commands.
I pushed your 2 suggestions, thank you.

But I don't understand the problem with the reload.
There's no redirect or render in the controller, so normally no reload.
In the Network tab of the Inspect Element, when you edit a vehicle, you see a POST method, then some GET when the vehicle#show is reloaded.
When I click on a fuel, I have only 1 POST in the Network tab, no GET.
If you add a **console.log("Page loaded")** at the beginning of any JS script, a new entry in the console will be added on each action (show vehicle, edit vehicle, edit or cancel), except when a fuel is clicked.
So maybe I'm wrong, but for me the page is not reloaded.

2021-03-30 12:55 UTC, JPS09 commented
> 
> 
> Wrong click, sorry for the close/reopen commands.
> I pushed your 2 suggestions, thank you.
> 
> But I don't understand the problem with the reload.
> There's no redirect or render in the controller, so normally no reload.
> In the Network tab of the Inspect Element, when you edit a vehicle, you see a POST method, then some GET when the vehicle#show is reloaded.
> When I click on a fuel, I have only 1 POST in the Network tab, no GET.
> If you add a **console.log("Page loaded")** at the beginning of any JS script, a new entry in the console will be added on each action (show vehicle, edit vehicle, edit or cancel), except when a fuel is clicked.
> So maybe I'm wrong, but for me the page is not reloaded.

Maybe the page is not loaded entirely but when you look at your tab, it shows that it's loading for a second with each click on a fuel and I think that's the form submitting default... We need to go through AJAX to avoid that I think

2021-03-30 13:14 UTC, sbriclot commented
> Maybe the page is not loaded entirely but when you look at your tab, it shows that it's loading for a second with each click on a fuel and I think that's the form submitting default... We need to go through AJAX to avoid that I think
The tab is moving due to the POST I think, but please check in the Network tab, there's nothing else than the POST method.
This is what we learned in the Ajax leason, with remote: true, you have less traffic in the netwrok tab when you use this helper.
In this case, we can't have less traffic than just a POST.

2021-03-31 10:38 UTC, JPS09 commented
> 
> 
> > Maybe the page is not loaded entirely but when you look at your tab, it shows that it's loading for a second with each click on a fuel and I think that's the form submitting default... We need to go through AJAX to avoid that I think.
> 
> The tab is moving due to the POST I think, but please check in the Network tab, there's nothing else than the POST method.
> This is what we learned in the Ajax leason, with remote: true, you have less traffic in the netwrok tab when you use this helper.
> In this case, we can't have less traffic than just a POST.

As we discussed through a call, I thought that we could prevent this tab refresh bu as you said, it would be a lot of work for little value. So I think that your PR is good to be merged

2021-03-31 10:38 UTC, JPS09 approved these changes

2021-04-05 15:17 UTC, merged